package toy.jlox;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, PLUS_PLUS, SEMICOLON, SLASH, STAR,

    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    IDENTIFIER, STRING, NUM,

    AND, BREAK, CLASS, CONTINUE, ELSE, FALSE, FUN,
    FOR, IF, NIL, OR, PRINT, PRINTLN, RETURN,
    SUPER, THIS, TRUE, VAR, WHILE,

    EOF
}
